## Run a conductor inside a job...

CP=.
CP+=:/opt/java
CP+=:/opt/java/mysql-connector/mysql-connector.jar
CP+=:/opt/java/jcm
CP+=:/opt/java/mysql-connector/mysql-connector.jar
CP+=:/opt/java/PostgreSQL/postgresql.jar
CP+=:/opt/java/jcm/jcm_data.jar
CP+=:/opt/java/SwingX/swingx.jar

DB_Server=HiCat

JVM_COND_PARMS="-cp $CP"
JVM_COND_PARMS+=" -Djava.awt.headless=true PIRL.Conductor.Conductor"
JVM_COND_PARMS+=" -Server $DB_Server"

# We don't need this with the job scheduler
# JVM_COND_PARMS+=" -Wait_to_Start"

# Only process one source per conductor
JVM_COND_PARMS+=" -Max_Source_Records 1"

HiRISE_ROOT?=/HiRISE
DB_Server?=HiCat

# The default CTX rule (CTX_Projector/Converter/Finalizer)
#CTX_%:
#	#PBS -q ctx -V
#	echo "foobar" > /home/pirl/cwvh/output.txt

CTX_Finalizer:
	#PBS -N CTX_Finalizer
	echo "pm_target_match = 42" > /home/pirl/cwvh/output.txt

# The default conductor rule
#%:
#	#PBS -q ${pm_target_match}
#	java $JVM_COND_PARMS -Pipeline ${pm_target_match} -Configuration $HiRISE_ROOT/Configuration/${pm_target_match}/${pm_target_match}.conf -Catalog HiRISE
