#!/bin/bash
# Run all tests in the local/ directory

function die {
  echo Error: "$@" >&2
  exit -1
}

cd $(dirname $0)

PBSMAKE=$(type -p pbsmake)

[[ -x "$PBSMAKE" ]] || die could not find pbsmake in path

echo using $PBSMAKE

find local/ -name \*.in | sed 's/.in$//' | xargs ./runTest
