#!/bin/bash
# Run a test of pbsmake (simply invoked via "pbsmake") and compare the output
# with known/expected output

function warn {
  echo Warning: "$@" >&2
}

for test_name in "$@"; do

  pbsmake -l -f "$test_name.in" > "$test_name.out"
  if [[ $? != 0 ]]; then
    warn pbsmake exited unhappily: $test_name
    continue
  fi

  diff -u "$test_name.expected" "$test_name.out" > "$test_name.diff"
  if [[ $? != 0 ]]; then
    warn $test_name produced unexpected output
  else
    rm -f "$test_name.diff" "$test_name.out"
  fi

done

