TARGET=target1

${TARGET}: target2 target3
	@export-all
	@name ${TARGET}
	echo target1

target2: target3
	@export-all
	@name \${TARGET}
	echo target2

target3: 
	@export-all
	@name target3
	echo target3
